### ISSUE TITLE
How to cite this work

### ISSUE THREAD

**Issue by diehlpk** [tjolsen/BlazeIterative#5]
Hi,

how should one cite this project in a research paper?

**Comment by tjolsen** [comment]
Honestly, there's nothing "novel" happening here, just a convenient collection of well-known algorithms that are designed to work smoothly with a high-quality linear algebra library that has received less community attention than some others (e.g. Eigen). Because of this, there's nothing to cite (yet?). I would, however, appreciate an acknowledgement (maybe link to the github page?). Also, let me know when you have a paper written that I can link to from the home page. I'd love to put a "Things that use BlazeIterative" section in the README until it (hopefully!) gets too large to maintain.
