### ISSUE TITLE
Const correctness

### ISSUE THREAD

**Issue by lordnn** [tjolsen/BlazeIterative#6]
Why the second parameter of solve() function is not const reference?

**Comment by tjolsen** [comment]
In short, because the tag is an input-output parameter. The IterativeTag, which is the base class for all solver-specific tag types, contains machinery for logging the convergence history during the iterations. The only restriction it places on the user is that the tag must be an lvalue reference, which means that you can't pass  a temporary object in as the last argument. This is, in my view, a trivial syntactic burden on the user compared to the ability to have the logging capability.

I'm happy to discuss it if you disagree, but for now I'm going to close the issue.

**Comment by lordnn** [comment]
Usually I use one-based index to count function parameters, so second parameter it's a Vector b

**Comment by tjolsen** [comment]
Ah, that's my bad. I, too, start counting at 1. I simply didn't look at it and assumed that you were talking about the tag. The vector 'b' could of course be const, but it doesn't buy you anything in terms of optimization because it can be cast away. However, from a style standpoint, it should be const, so I'll go ahead and change it. I was probably just being lazy when I wrote it.

Thanks for bringing this to my attention!
