### ISSUE TITLE
Solve with guess

### ISSUE THREAD

**Issue by lordnn** [tjolsen/BlazeIterative#7]
I suggest to add solve with guess function, for example:
`template<typename MatrixType, typename T, typename TagType> DynamicVector<T> `
`solve(const MatrixType &A, const DynamicVector<T> &b, const DynamicVector<T> &x0, TagType &tag)`
`{`
`    DynamicVector<T> x(x0);`
`    solve_inplace(x, A, b, tag);`

`    return x;`
`};`

**Comment by tjolsen** [comment]
As noted in the documentation (comments) for `solve` and `solve_inplace`, you should just use `solve_inplace` directly. Accepting an initial guess in the `solve` function would simply allocate more memory, which would be wasteful since the user has already allocated memory for the initial guess.

Am I missing a use case that couldn't be handled using the solve_inplace method?

**Comment by lordnn** [comment]
M-m-m may be `solve` and `solve_inplace` has different kind of return value and can't be use as a callback (one instead of other).

Ok, currently I have no answer on your question, and `solve_inplace` will be enough.

**Comment by tjolsen** [comment]
I mean, if you're actually using this, then let me know if there's something that would be genuinely useful. I just can't think of a reason why the available functions would not be sufficient. If a `solve` function with an initial guess would be useful in a place where `solve_inplace` is insufficient, then it can certainly be added. However, I'd like the function signature to be:

```c++
template<typename MatrixType, typename T, typename TagType>
DynamicVector<T> solve(
        const MatrixType &A, 
        const DynamicVector<T> &b, 
        DynamicVector<T> &&x0,  // <-- rvalue reference, b/c I'm going to steal the memory
        TagType& tag
);
```

I prefer any extra allocation to be done in the user code if possible, not the library code. The basic `solve` method is there for convenience, since memory would have needed to be allocated for an initial guess regardless. This would make it a bit clunky to use the function, but the rvalue reference parameter
makes the user painfully aware that they no longer own the memory, since they'd have to call it like this:

```c++
// ...make A, b...

DynamicVector<double> x0(N);
// fill x0 here...

DynamicVector<double> x = solve(A, b, std::move(x0), tag);
```

Thoughts?

**Comment by lordnn** [comment]
Your proposal is reasonable. But currently `solve_inplace` is enough for me.
